### ISSUE TITLE
Why For-loop has many successive statements ?

### ISSUE THREAD

**Issue by alamenai** [jasmineannrivera/mintbean-weather-hackathon#1]
`For` loop at the line `47` has 10 successive statements that reduce the code readability and break SOLID and KISS principles.

It would be better if we extract it into another function `createWeatherHTML` to do the job of creation DOM element.

**Comment by jasmineannrivera** [comment]
@MenaiAla Thanks for your comment!  I am not too familiar with this method, but I will do more research so I can implement it.  I am always looking to improve my code so thank you for taking the time to read through it and for teaching me something new.

**Comment by alamenai** [comment]
@Jasmin, for your next projects, when you implement a function be sure that your function does **one thing and does it well**.
